### ISSUE TITLE
Feature GFFs should include exon records

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/datastore#26]
For compatibility with the InterMine GFF loader, which makes no assumptions about biology, we should have exon records in the GFFs in addition to CDS records. As it stands now, e.g. for lupan, no exons get loaded, which would probably annoy some miners.

**Comment by cann0010** [comment]
Question about this Sam: for some GFFs I was looking at over the weekend, the exon lines were redundant with the CDS and UTR lines (redundant = having the same coordinates as). Phytozome maintains the "with-exon" version (at least for Glycine max and Phaseolus vulgaris), and I deleted them during the weekend Data Store cleanup. Confirming: we need those "with-exon" versions? Slightly irritating to have to keep the somewhat-bloated exon versions around ...

**Comment by cann0010** [comment]
Also (pinging @adf-ncgr ): would the with-exon versions become the "gene_model_main.gff3" instances?

**Comment by sammyjava** [comment]
Yeah, it's "bloat" but "required bloat" because the InterMine loader doesn't infer anything. It just loads the feature types as given. It's just bytes, anyway, and disk is cheap. I've been trying to load lupan from ` lupan.Tanjil.gnm1.ann1.nnV9.gene_models_main.gff3`.

**Comment by cann0010** [comment]
Ok. Tomorrow ...

**Comment by sammyjava** [comment]
No hurry, just hitting the CyVerse datastore with the IM loader to find issues. Another key thing is the lack of ID attributes on CDSes (separate issue). And ID is needed on exons as well as anything else to be loaded, since IM needs a primaryIdentifier, which it gets from the unique ID.

**Comment by adf-ncgr** [comment]
FWIW, we have some files that don't have exons because they came to us that way and some that don't have exons because they came in two flavors and in the latest round of fussing, I arbitrarily chose the less bloated versions. The latter should be relatively easy to redo with the more bloated versions, the former we'll have to handle somewhat similarly to the way we add gene records when all we're given are mRNA records (also relatively easy, just hasn't been a concern previously).

With respect to IDs, we may wish to enunciate a standard for what they should look like (if indeed we care). FWIW, what I am doing now for Name/ID in the gff context is:
-value originally associated with Name attribute (if exists) is used as base; if no Name attribute exists, but an ID exists, we use the latter instead as a base.
-full prefixing (gensp.genotype.gnmX.annY.) prepended to form new ID value; (note that if the Name attribute was used above, this likely means the old ID value is simply overwritten in "lossy" fashion which is probably OK, given that IDs are not required to be meaningful, just unique in the context of the file). 
-"just enough" prefixing (usually gensp. sometimes gensp.genotype.) added to Name value
-Parent attributes are converted under the assumption that they reference IDs and get whatever the ID has been converted to (ie in the case of fullprefix.originalName)
-if no Name or ID exists, nothing will be done to add them (Parent attributes will still be converted if they exist)
I believe the behavior described is what we've essentially agreed to, even if we didn't understand the ramifications of agreeing to it at the time; the last clause may require amendment if we agree that it makes sense to push the intermine requirements upstream into the datastore. I have no objection to it, and would be happy to adopt something like the phytozome conventions for exon/CDS/UTR identification. I should note, however that since Phytozome only provides IDs and does not provide Names for their exon/CDS/UTR, I just noticed that they get pretty godawful using the scheme described above (which works well for their Name'd gene/mRNAs), e.g. whereas their:
whereas their original:
ID=Glyma.01G000400.Wm82.a2.v1;Name=Glyma.01G000400
becomes the elegant and in all ways inoffensive
ID=glyma.Wm82.gnm2.ann1.Glyma.01G000400;Name=glyma.Glyma.01G000400
on the other hand, their delightful:
ID=Glyma.01G000400.1.Wm82.a2.v1.CDS.1; etc.
becomes the "liquid pain":
ID=glyma.Wm82.gnm2.ann1.Glyma.01G000400.1.Wm82.a2.v1.CDS.1;Name=glyma.Glyma.01G000400.1.Wm82.a2.v1.CDS.1

according the the best generic logic I've been able to devise (as described above).
I tend to think that below the transcript entities (ie exon/CDS/UTR) won't get referenced externally, but I guess that's not much of an excuse for anonymizing them.

open to suggestions that strike the appropriate balance between mattering to anyone and level of additional effort...

**Comment by sammyjava** [comment]
I love `liquid pain`! I'm just running the files against the IM FASTA and GFF loaders - we need not impose InterMine loadability on the datastore, but it seems valuable to record what doesn't work. I can always write custom loaders to do the required munging and re-typing and stuff, but that's not what a novice miner will have in her stock InterMine install. So the high-level question "do we care about stock InterMine loadability" should probably be answered before facing liquid pain.

**Comment by cann0010** [comment]
What do y'all think about a script to derive the appropriately-formatted, appropriately-ID'd exon GFFs from the gene_models_main.gff3 (for the Data Store)? It could probably be done with a few lines of awk (though if complexities arise, perl is the usual fallback). The exon files are available for some species but not others, so we probably need such a script in any case - and if we have it, we might as well use it as THE way to derive such files.

**Comment by sammyjava** [comment]
Sounds groovacious to me - and IDs for other types that only currently have parent attributes, like CDSes.

On the `liquid pain` front I was thinking of modifying the IM GFF3 loader to handle non-ID cases since that only extends its current functionality and may be generally appreciated; I could easily talk the IM Politburo into accepting a PR on that, I'm sure, since it has no effect on current usage (plus there's a bug where **one** record gets loaded as `null`.

I figured *Parent*.*start*.*finish* would be a reproducible naming scheme, e.g.
```
lupan.Tanjil.gnm1.NLL-06	lupan.Tanjil.gnm1.ann1.nnV9	mRNA	6615279	6617817	0.999832	-	.	Parent=lupan.Tanjil.gnm1.ann1.Lup005556;ID=lupan.Tanjil.gnm1.ann1.Lup005556.1;Name=lupan.Lup005556.1;source_id=Lupinus_GLEAN_10010521;identical_support_id=CUFF13.142.1;part_support_id=CUFF13.142.2;Ontology_term=GO:0003723,GO:0003735,GO:0005622,GO:0005840,GO:0006412
lupan.Tanjil.gnm1.NLL-06	lupan.Tanjil.gnm1.ann1.nnV9	CDS	6615439	6615558	.	-	.	Parent=lupan.Tanjil.gnm1.ann1.Lup005556.1
```
becomes
```
lupan.Tanjil.gnm1.NLL-06	lupan.Tanjil.gnm1.ann1.nnV9	mRNA	6615279	6617817	0.999832	-	.	Parent=lupan.Tanjil.gnm1.ann1.Lup005556;ID=lupan.Tanjil.gnm1.ann1.Lup005556.1;Name=lupan.Lup005556.1;source_id=Lupinus_GLEAN_10010521;identical_support_id=CUFF13.142.1;part_support_id=CUFF13.142.2;Ontology_term=GO:0003723,GO:0003735,GO:0005622,GO:0005840,GO:0006412
lupan.Tanjil.gnm1.NLL-06	lupan.Tanjil.gnm1.ann1.nnV9	CDS	6615439	6615558	.	-	.	Parent=lupan.Tanjil.gnm1.ann1.Lup005556.1;ID=lupan.Tanjil.gnm1.ann1.Lup005556.1.6615439.6615558
```
etc.

**Comment by adf-ncgr** [comment]
explicit exons not required. If no exons provided, UTRs SHOULD be represented (if modeled).
